[model_clients]
  [model_clients.orchestrator_client]
    model = "gpt-4o-mini"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000

  [model_clients.planning_client]
    model = "gpt-4o-mini"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000
    
  [model_clients.reflection_client]
    model = "gpt-4o-mini"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000
  
  [model_clients.code_client]
    model = "gpt-4.1-2025-04-14"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000

  [model_clients.step_triage_client]
    model = "gpt-4o-mini"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000
  
  [model_clients.single_tool_use_client]
    model = "gpt-4o-mini"
    base_url = "${OPENAI_BASE_URL}"
    api_key = "${OPENAI_API_KEY}"
    max_tokens = 16000
    parallel_tool_calls = false

  [model_clients.html_generator_client]
    model = "anthropic/claude-opus-4"
    auth_token = "${OPENAI_API_KEY}"
    base_url = "https://api.aimlapi.com" 
    max_tokens = 20000